### ISSUE TITLE
Could not find com.android.support:support-v4:23.4.0

### ISSUE THREAD

**Issue by chrisschaub** [phonegap/build#522]
So a build that worked yesterday, same source code, does not work today.

Could not find com.android.support:support-v4:23.4.0

Build Date: 2016-05-25 01:46:57 +0000

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:23.4.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
     Required by:
         :project:unspecified
   > Could not find com.android.support:support-v4:23.4.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
     Required by:
         :project:unspecified > com.android.support:support-v13:23.2.1
   > Could not find com.android.support:support-v4:23.4.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
     Required by:
         :project:unspecified > com.google.android.gms:play-services-analytics:8.4.0 > com.google.android.gms:play-services-basement:8.4.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

App Id: 1919084

**Comment by chrisschaub** [comment]
Issue with version 1.6.4 of phonegap-push-plugin on phonegap build.

**Comment by Adrion** [comment]
Any issue source ?

**Comment by Adrion** [comment]
Nm ^^ : [#928](https://github.com/phonegap/phonegap-plugin-push/issues/928)

**Comment by goya** [comment]
this issue has been fixed.  PLEASE be sure to pin your plugin versions to a specific version!

**Comment by devsimatech** [comment]
Not fixed for me. Getting same error. I'm using:

<vs:plugin name="phonegap-plugin-push" version="1.6.4" src="https://github.com/phonegap/phonegap-plugin-push.git">

**Comment by devsimatech** [comment]
name="phonegap-plugin-push" version="1.6.4" src="https://github.com/phonegap/phonegap-plugin-push.git"

**Comment by goya** [comment]
i am unable to replicate your issue @devsimatech 

please start an issue at https://forums.adobe.com/community/phonegap/build so we can troubleshoot.  please include your app # so we can check out your build logs.
